import streamlit as st
from PIL import Image
import plotly.express as px
import pandas as pd


def configure_model():

    col1, col2 = st.columns(spec=(1,2), gap="large")

    with col1:
        image = Image.open("drug_ai/Durg_Toxicity/Images/Model.png")
        image = image.resize((360, 750))
        st.image(image)

    with col2:
        st.title("Configuration🪛")
        Config_text = (
            "<p style='font-size: 20px;'>Because estimating a chemical compound's toxicity is a critical task, we must make sure that investigating the predictions generated by this module doesn't waste any computational power or expert human work. The option to manually specify the threshold value for the anticipated outcome is provided below.</p>")
        st.markdown(Config_text, unsafe_allow_html=True)

        # Input for the Facilities based recommendation system weight
        facilities_recommendation_wt = st.slider("Adjust the Dropout ratio of Model (%)",
                                                 min_value=40,
                                                 max_value=95,
                                                 value=50,
                                                 step=1,
                                                 key="facilities_recommendation_wt",
                                                 )

        # Create data for the pie chart
        data = {
            "Categories": ["Dropout Ratio", "~"],
            "Weights": [facilities_recommendation_wt, 100 - facilities_recommendation_wt],
        }

        # Create a DataFrame from the data
        df = pd.DataFrame(data)
        custom_colors = ["#AEF359", "#03C04A"]

        # Create a dynamic pie chart using Plotly Express
        fig = px.pie(
            df,
            names="Categories",
            values="Weights",
            title="Model output threshold Configuration",
            color_discrete_sequence=custom_colors,
        )
        st.plotly_chart(fig, use_container_width=True)


configure_model()